#!/bin/bash
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

if [ $# -ne 1 ]; then
    echo "Missing param, provide gitlab repo name"
    echo "Note: This script uses MY_GITLAB_TOKEN and MY_GITLAB_USER env vars"
    exit
fi

REPO=$1
HEADER="PRIVATE-TOKEN: $MY_GITLAB_TOKEN"
URL=https://gitlab.com/api/v4/projects

# Lookup the project id so we can use it below
PID=$(curl -s -L --header "$HEADER" "$URL/$MY_GITLAB_USER%2F$REPO" | jq ".id")

function setVars() {
    NAME=$1
    VALUE=$2
    #echo "setting $NAME in https://gitlab.com/$MY_GITLAB_USER/$REPO"

   # for setting or deleting short values do it manually 
    if (( "${#VALUE}" > 0 && "${#VALUE}" < 8 )); then   
        CURRENT_VALUE=$(curl -s --header "PRIVATE-TOKEN: $MY_GITLAB_TOKEN" "$URL/$PID/variables/$NAME" | jq .value)
        if [[ "$CURRENT_VALUE" != "$VALUE" ]]; then
            echo "OK: Skipping short value $NAME as it is already set to <$VALUE>"
        else 
            echo "WARNING - SET $NAME manually to <$VALUE> as the gitlab API fails on short values"
        fi 
        return
    fi  

    # Delete first because if the secret already exists then its value
    # won't be changed by the POST below
    curl -s --request DELETE --header "$HEADER" "$URL/$PID/variables/$NAME"  > /dev/null 2>&1
 
    if (( "${#VALUE}" == 0 )); then    
        echo "WARNING - Deleting $NAME manually as value is empty"  
        return
    fi  

    # Set the new key/value
    CURRENT_VALUE=$(curl -s --request POST --header "$HEADER" "$URL/$PID/variables" \
        --form "key=$NAME" --form "value=$VALUE" --form "masked=true" --form "raw=true" | jq .value)
    
    echo "SET $NAME to <$CURRENT_VALUE>"
}

setVars ROX_CENTRAL_ENDPOINT $ROX_CENTRAL_ENDPOINT
setVars ROX_API_TOKEN $ROX_API_TOKEN

setVars GITOPS_AUTH_PASSWORD $MY_GITLAB_TOKEN
setVars GITOPS_AUTH_USERNAME $MY_GITLAB_USER

setVars QUAY_IO_CREDS_USR $QUAY_IO_CREDS_USR
setVars QUAY_IO_CREDS_PSW $QUAY_IO_CREDS_PSW

setVars COSIGN_SECRET_PASSWORD $COSIGN_SECRET_PASSWORD
setVars COSIGN_SECRET_KEY $COSIGN_SECRET_KEY
setVars COSIGN_PUBLIC_KEY $COSIGN_PUBLIC_KEY

setVars TRUSTIFICATION_BOMBASTIC_API_URL "$TRUSTIFICATION_BOMBASTIC_API_URL"
setVars TRUSTIFICATION_OIDC_ISSUER_URL "$TRUSTIFICATION_OIDC_ISSUER_URL"
setVars TRUSTIFICATION_OIDC_CLIENT_ID "$TRUSTIFICATION_OIDC_CLIENT_ID"
setVars TRUSTIFICATION_OIDC_CLIENT_SECRET "$TRUSTIFICATION_OIDC_CLIENT_SECRET"
setVars TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION "$TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION"

#bash $SCRIPTDIR/glab-get-vars $1
